[project]
name = "python-grpc"
version = "0.1.0"
description = ""
authors = [
    {name = "Farrel Augusta Dinata",email = "farrel.apeiron@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "fastapi (>=0.141.1,<0.142.0)",
    "grpcio (>=1.83.0,<2.0.0)",
    "grpcio-tools (>=1.83.0,<2.0.0)",
    "protobuf (>=7.35.1,<8.0.0)",
    "uvicorn (>=0.52.4,<0.53.0)",
    "grpcio-health-checking (>=1.83.1,<2.0.0)",
    "paho-mqtt (>=2.1.0,<3.0.0)",
]

[tool.poetry]
packages = [{include = "python_grpc", from = "src"}]

[tool.pyrefly]
preset = "strict"
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
project-excludes = [
    "**/python_grpc/proto/*_pb2*.py*",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pyrefly (>=1.2.0,<2.0.0)",
    "ruff (>=0.14.0,<1.0.0)",
    "types-grpcio (>=1.83.0.20260730,<2.0.0.0)",
    "types-protobuf (>=7.34.1.20260518,<8.0.0.0)",
    "grpcio-health-checking (>=1.83.1,<2.0.0)",
    "httpx (>=0.28.1,<0.29.0)",
    "pytest (>=9.1.1,<10.0.0)",
    "pytest-asyncio (>=1.4.0,<2.0.0)",
    "pytest-cov (>=7.1.0,<8.0.0)",
    "types-grpcio-health-checking (>=1.0.0.20260518,<2.0.0.0)"
]

[tool.ruff]
target-version = "py313"
line-length = 88
extend-exclude = [
    "src/python_grpc/proto/*_pb2*.py",
    "src/python_grpc/proto/*_pb2*.pyi",
]

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "UP",   # pyupgrade
]
ignore = [
    "E501", # line-too-long handled by ruff format
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"


[tool.pytest.ini_options]
minversion = "8.0"
testpaths = ["tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

