# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from python_grpc.proto import pzem_004t_pb2 as python__grpc_dot_proto_dot_pzem__004t__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in python_grpc/proto/pzem_004t_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeviceTelemetryStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportReading = channel.unary_unary(
                '/pzem004t.DeviceTelemetry/ReportReading',
                request_serializer=python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.SerializeToString,
                response_deserializer=python__grpc_dot_proto_dot_pzem__004t__pb2.Ack.FromString,
                _registered_method=True)
        self.ReportReadings = channel.stream_unary(
                '/pzem004t.DeviceTelemetry/ReportReadings',
                request_serializer=python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.SerializeToString,
                response_deserializer=python__grpc_dot_proto_dot_pzem__004t__pb2.BatchSummary.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/pzem004t.DeviceTelemetry/Subscribe',
                request_serializer=python__grpc_dot_proto_dot_pzem__004t__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.stream_stream(
                '/pzem004t.DeviceTelemetry/StreamTelemetry',
                request_serializer=python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.SerializeToString,
                response_deserializer=python__grpc_dot_proto_dot_pzem__004t__pb2.Ack.FromString,
                _registered_method=True)


class DeviceTelemetryServicer:
    """Missing associated documentation comment in .proto file."""

    def ReportReading(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportReadings(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceTelemetryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportReading': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportReading,
                    request_deserializer=python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.FromString,
                    response_serializer=python__grpc_dot_proto_dot_pzem__004t__pb2.Ack.SerializeToString,
            ),
            'ReportReadings': grpc.stream_unary_rpc_method_handler(
                    servicer.ReportReadings,
                    request_deserializer=python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.FromString,
                    response_serializer=python__grpc_dot_proto_dot_pzem__004t__pb2.BatchSummary.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=python__grpc_dot_proto_dot_pzem__004t__pb2.SubscribeRequest.FromString,
                    response_serializer=python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.SerializeToString,
            ),
            'StreamTelemetry': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.FromString,
                    response_serializer=python__grpc_dot_proto_dot_pzem__004t__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pzem004t.DeviceTelemetry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pzem004t.DeviceTelemetry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeviceTelemetry:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportReading(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pzem004t.DeviceTelemetry/ReportReading',
            python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.SerializeToString,
            python__grpc_dot_proto_dot_pzem__004t__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportReadings(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pzem004t.DeviceTelemetry/ReportReadings',
            python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.SerializeToString,
            python__grpc_dot_proto_dot_pzem__004t__pb2.BatchSummary.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pzem004t.DeviceTelemetry/Subscribe',
            python__grpc_dot_proto_dot_pzem__004t__pb2.SubscribeRequest.SerializeToString,
            python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/pzem004t.DeviceTelemetry/StreamTelemetry',
            python__grpc_dot_proto_dot_pzem__004t__pb2.ReadingReport.SerializeToString,
            python__grpc_dot_proto_dot_pzem__004t__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
