# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: python_grpc/proto/pzem_004t.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'python_grpc/proto/pzem_004t.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!python_grpc/proto/pzem_004t.proto\x12\x08pzem004t\"\xc3\x01\n\rReadingReport\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x02 \x01(\t\x12\x19\n\x11timestamp_unix_ms\x18\x03 \x01(\x03\x12\x0f\n\x07voltage\x18\x04 \x01(\x01\x12\x0f\n\x07\x63urrent\x18\x05 \x01(\x01\x12\x14\n\x0c\x61\x63tive_power\x18\x06 \x01(\x01\x12\x0e\n\x06\x65nergy\x18\x07 \x01(\x01\x12\x11\n\tfrequency\x18\x08 \x01(\x01\x12\x14\n\x0cpower_factor\x18\t \x01(\x01\"D\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1b\n\x13received_at_unix_ms\x18\x03 \x01(\x03\"L\n\x0c\x42\x61tchSummary\x12\x10\n\x08received\x18\x01 \x01(\x05\x12\x10\n\x08rejected\x18\x02 \x01(\x05\x12\x18\n\x10\x61vg_active_power\x18\x03 \x01(\x01\"%\n\x10SubscribeRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t2\x92\x02\n\x0f\x44\x65viceTelemetry\x12\x37\n\rReportReading\x12\x17.pzem004t.ReadingReport\x1a\r.pzem004t.Ack\x12\x43\n\x0eReportReadings\x12\x17.pzem004t.ReadingReport\x1a\x16.pzem004t.BatchSummary(\x01\x12\x42\n\tSubscribe\x12\x1a.pzem004t.SubscribeRequest\x1a\x17.pzem004t.ReadingReport0\x01\x12=\n\x0fStreamTelemetry\x12\x17.pzem004t.ReadingReport\x1a\r.pzem004t.Ack(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'python_grpc.proto.pzem_004t_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READINGREPORT']._serialized_start=48
  _globals['_READINGREPORT']._serialized_end=243
  _globals['_ACK']._serialized_start=245
  _globals['_ACK']._serialized_end=313
  _globals['_BATCHSUMMARY']._serialized_start=315
  _globals['_BATCHSUMMARY']._serialized_end=391
  _globals['_SUBSCRIBEREQUEST']._serialized_start=393
  _globals['_SUBSCRIBEREQUEST']._serialized_end=430
  _globals['_DEVICETELEMETRY']._serialized_start=433
  _globals['_DEVICETELEMETRY']._serialized_end=707
# @@protoc_insertion_point(module_scope)
